### ISSUE TITLE
Article overview in the wrong order

### ISSUE THREAD

**Issue by gazpod100** [markusoelhafen/100-meeple#19]
The newest article is on the last page in the overview, the oldest on the first page. please change.

**Comment by markusoelhafen** [comment]
Issue in admin panel. Can be solved by adding a `home.yml` in `/site/blueprints/` and pasting this code:
```
title: Home

pages:
  template: article
  sort: flip
  num: date

options:
  template: false
  status: false

icon: home

fields:
  title:
    label: Title
    type:  text

  intro:
    label: Intro
    type:  textarea

  text:
    label: Text
    type:  textarea
```

`sort: flip` changes the order of the articles in home.
